Django/website_flutter/accounts/urls.py
from django.urls import path
from .views import *

app_name = 'accounts'

urlpatterns = [
    path('login/', login_view, name='login'),
    path('register/', register_view, name='register'),
    path('logout/', logout_view, name='logout'),
]

Django/website_flutter/home/urls.py
from django.urls import path
from .views import *

app_name = 'home'

urlpatterns = [
    path('', home_view, name='home'),
]

Django/website_flutter/post/urls.py
from django.urls import path
from .views import *

app_name = 'post'

urlpatterns = [
    path('index/', post_index, name='index'),
    path('detail/<str:slug>', post_detail, name='detail'),
    path('create/', post_create, name='create'),
    path('update/<str:slug>', post_update, name='update'),
    path('delete/<str:slug>', post_delete, name='delete'),
    path('confirm/', post_confirm_page, name='confirm_page'),
    path('confirm/<str:slug>', post_confirm, name='confirm'),
]

Django/website_flutter/website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('post/', include('post.urls')),
    path('accounts/', include('accounts.urls')),

    path('api/post/', include('post.api.urls')),
    path('api/accounts/', include('accounts.api.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Django/website_flutter/home/models.py
from django.db import models

# Create your models here.

Django/website_flutter/home/views.py
from django.shortcuts import render


def home_view(request):
    return render(request, 'home.html', {})

Django/website_flutter/templates/base.html
<!DOCTYPE html>
<html lang="en">

{% load static %}

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Website Flutter</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'business-casual.min.css' %} " rel="stylesheet">

  </head>

  <body>

    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Website Flutter</span>
    </h1>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
      <div class="container">
        <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="{% url 'home:home' %}">Website Flutter</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav mx-auto">
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'home:home' %}">Home</a>
            </li>
            {% if request.user.is_authenticated %}
              <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'post:index' %}">Posts</a>
              </li>
              <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'post:create' %}">Add Post</a>
              </li>
              {% if request.user.is_superuser %}
              <li class="nav-item px-lg-4">
                <a class="nav-link text-uppercase text-expanded" href="{% url 'post:confirm_page' %}">Confirm Posts</a>
              </li>
              {% endif %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:logout' %}">Log Out</a>
            </li>
            {% else %}
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:register' %}">Register</a>
            </li>
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="{% url 'accounts:login' %}">Log In</a>
            </li>
            {% endif %}
            <!--
            <li class="nav-item px-lg-4">
              <a class="nav-link text-uppercase text-expanded" href="">Contact</a>
            </li>
            -->
          </ul>
        </div>
      </div>
    </nav>

    {% block content %}
    {% endblock %}

    <footer class="footer text-faded text-center py-5">
      <div class="container">
        <p class="m-0 small">Copyright &copy; Your Website 2021</p>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'jquery.min.js' %}"></script>
    <script src="{% static 'bootstrap.bundle.min.js' %}"></script>

    <!-- Script to highlight the active date in the hours list -->
    <script>
      $('.list-hours li').eq(new Date().getDay()).addClass('today');
    </script>

  </body>

</html>

Django/website_flutter/templates/home.html
{% extends 'base.html'%}

{% block content %}

{% load static %}

  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <img class="intro-img img-fluid mb-3 mb-lg-0 rounded" src="{% static 'img/flutter.png' %}" alt="">
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Why Flutter?</span>
          </h2>
          <p class="mb-3">Flutter is faster than many other application development frameworks. With its “hot reload” feature, you can experiment, build UIs, add/remove features, test and fix bugs faster. Thus reducing the overall app development time.
          </p>
        </div>
      </div>
    </div>
  </section>

{% endblock %}